//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.03 at 07:22:15 AM WAT 
//


package com.uan.interfaces;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="stationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="dock" type="{http://interfaces.uan.com}DockType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stationId",
    "dock"
})
@XmlRootElement(name = "AddDockRequest")
public class AddDockRequest {

    protected long stationId;
    @XmlElement(required = true)
    protected DockType dock;

    /**
     * Gets the value of the stationId property.
     * 
     */
    public long getStationId() {
        return stationId;
    }

    /**
     * Sets the value of the stationId property.
     * 
     */
    public void setStationId(long value) {
        this.stationId = value;
    }

    /**
     * Gets the value of the dock property.
     * 
     * @return
     *     possible object is
     *     {@link DockType }
     *     
     */
    public DockType getDock() {
        return dock;
    }

    /**
     * Sets the value of the dock property.
     * 
     * @param value
     *     allowed object is
     *     {@link DockType }
     *     
     */
    public void setDock(DockType value) {
        this.dock = value;
    }

}
