//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.03 at 07:22:15 AM WAT 
//


package com.uan.interfaces;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.uan.interfaces package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.uan.interfaces
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllServicesRequest }
     * 
     */
    public GetAllServicesRequest createGetAllServicesRequest() {
        return new GetAllServicesRequest();
    }

    /**
     * Create an instance of {@link GetAllServicesResponse }
     * 
     */
    public GetAllServicesResponse createGetAllServicesResponse() {
        return new GetAllServicesResponse();
    }

    /**
     * Create an instance of {@link ServiceDetails }
     * 
     */
    public ServiceDetails createServiceDetails() {
        return new ServiceDetails();
    }

    /**
     * Create an instance of {@link GetStationUrlRequest }
     * 
     */
    public GetStationUrlRequest createGetStationUrlRequest() {
        return new GetStationUrlRequest();
    }

    /**
     * Create an instance of {@link GetStationUrlResponse }
     * 
     */
    public GetStationUrlResponse createGetStationUrlResponse() {
        return new GetStationUrlResponse();
    }

    /**
     * Create an instance of {@link GetStationRequest }
     * 
     */
    public GetStationRequest createGetStationRequest() {
        return new GetStationRequest();
    }

    /**
     * Create an instance of {@link GetStationResponse }
     * 
     */
    public GetStationResponse createGetStationResponse() {
        return new GetStationResponse();
    }

    /**
     * Create an instance of {@link StationType }
     * 
     */
    public StationType createStationType() {
        return new StationType();
    }

    /**
     * Create an instance of {@link AddDockRequest }
     * 
     */
    public AddDockRequest createAddDockRequest() {
        return new AddDockRequest();
    }

    /**
     * Create an instance of {@link DockType }
     * 
     */
    public DockType createDockType() {
        return new DockType();
    }

    /**
     * Create an instance of {@link AddDockResponse }
     * 
     */
    public AddDockResponse createAddDockResponse() {
        return new AddDockResponse();
    }

    /**
     * Create an instance of {@link DeleteDockRequest }
     * 
     */
    public DeleteDockRequest createDeleteDockRequest() {
        return new DeleteDockRequest();
    }

    /**
     * Create an instance of {@link DeleteDockResponse }
     * 
     */
    public DeleteDockResponse createDeleteDockResponse() {
        return new DeleteDockResponse();
    }

    /**
     * Create an instance of {@link AlterStateDockInUpBikeRequest }
     * 
     */
    public AlterStateDockInUpBikeRequest createAlterStateDockInUpBikeRequest() {
        return new AlterStateDockInUpBikeRequest();
    }

    /**
     * Create an instance of {@link AlterStateDockInUpBikeResponse }
     * 
     */
    public AlterStateDockInUpBikeResponse createAlterStateDockInUpBikeResponse() {
        return new AlterStateDockInUpBikeResponse();
    }

    /**
     * Create an instance of {@link AlterStateDockInDownBikeRequest }
     * 
     */
    public AlterStateDockInDownBikeRequest createAlterStateDockInDownBikeRequest() {
        return new AlterStateDockInDownBikeRequest();
    }

    /**
     * Create an instance of {@link AlterStateDockInDownBikeResponse }
     * 
     */
    public AlterStateDockInDownBikeResponse createAlterStateDockInDownBikeResponse() {
        return new AlterStateDockInDownBikeResponse();
    }

    /**
     * Create an instance of {@link LockBikeRequest }
     * 
     */
    public LockBikeRequest createLockBikeRequest() {
        return new LockBikeRequest();
    }

    /**
     * Create an instance of {@link LockBikeResponse }
     * 
     */
    public LockBikeResponse createLockBikeResponse() {
        return new LockBikeResponse();
    }

    /**
     * Create an instance of {@link UnlockBikeRequest }
     * 
     */
    public UnlockBikeRequest createUnlockBikeRequest() {
        return new UnlockBikeRequest();
    }

    /**
     * Create an instance of {@link UnlockBikeResponse }
     * 
     */
    public UnlockBikeResponse createUnlockBikeResponse() {
        return new UnlockBikeResponse();
    }

    /**
     * Create an instance of {@link LevantarBicicletaRequest }
     * 
     */
    public LevantarBicicletaRequest createLevantarBicicletaRequest() {
        return new LevantarBicicletaRequest();
    }

    /**
     * Create an instance of {@link LevantarBicicletaResponse }
     * 
     */
    public LevantarBicicletaResponse createLevantarBicicletaResponse() {
        return new LevantarBicicletaResponse();
    }

    /**
     * Create an instance of {@link EntregarBicicletaRequest }
     * 
     */
    public EntregarBicicletaRequest createEntregarBicicletaRequest() {
        return new EntregarBicicletaRequest();
    }

    /**
     * Create an instance of {@link EntregarBicicletaResponse }
     * 
     */
    public EntregarBicicletaResponse createEntregarBicicletaResponse() {
        return new EntregarBicicletaResponse();
    }

    /**
     * Create an instance of {@link CreateStationRequest }
     * 
     */
    public CreateStationRequest createCreateStationRequest() {
        return new CreateStationRequest();
    }

    /**
     * Create an instance of {@link CreateStationResponse }
     * 
     */
    public CreateStationResponse createCreateStationResponse() {
        return new CreateStationResponse();
    }

    /**
     * Create an instance of {@link CreateUserRequest }
     * 
     */
    public CreateUserRequest createCreateUserRequest() {
        return new CreateUserRequest();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link CreateUserResponse }
     * 
     */
    public CreateUserResponse createCreateUserResponse() {
        return new CreateUserResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetSaldoRequest }
     * 
     */
    public GetSaldoRequest createGetSaldoRequest() {
        return new GetSaldoRequest();
    }

    /**
     * Create an instance of {@link GetSaldoResponse }
     * 
     */
    public GetSaldoResponse createGetSaldoResponse() {
        return new GetSaldoResponse();
    }

    /**
     * Create an instance of {@link SendPointRequest }
     * 
     */
    public SendPointRequest createSendPointRequest() {
        return new SendPointRequest();
    }

    /**
     * Create an instance of {@link SendPointResponse }
     * 
     */
    public SendPointResponse createSendPointResponse() {
        return new SendPointResponse();
    }

    /**
     * Create an instance of {@link GetAllUsersRequest }
     * 
     */
    public GetAllUsersRequest createGetAllUsersRequest() {
        return new GetAllUsersRequest();
    }

    /**
     * Create an instance of {@link GetAllUsersResponse }
     * 
     */
    public GetAllUsersResponse createGetAllUsersResponse() {
        return new GetAllUsersResponse();
    }

    /**
     * Create an instance of {@link UserXSD }
     * 
     */
    public UserXSD createUserXSD() {
        return new UserXSD();
    }

    /**
     * Create an instance of {@link VerifyUserRequest }
     * 
     */
    public VerifyUserRequest createVerifyUserRequest() {
        return new VerifyUserRequest();
    }

    /**
     * Create an instance of {@link VerifyUserResponse }
     * 
     */
    public VerifyUserResponse createVerifyUserResponse() {
        return new VerifyUserResponse();
    }

}
