//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.03 at 07:22:15 AM WAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://interfaces.uan.com", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.uan.interfaces;
