//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.04 at 01:06:20 PM WAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.webservices.com/requests/users", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.webservices.requests.users;
